=head1 VERSION

Version 0.01

=head1 SYNOPSIS

HYSCRIPT to import JSON from a hydll webservices
  
     
=head1 Usage

Specify the function as you would a perl JSONCall. 
See the Hydstra helpfile: HYDLLP - Flat DLL Interface to Hydstra

=head1 Screenshot 

=begin HTML

<p><img src="https://github.com/Chromicon/jsonimp/blob/master/images/PSC.PNG"
width="500" height="250" alt="PSC" /></p>

=end HTML
