=head1 Version

Version 0.01

=head1 Synopsis

HYSCRIPT to import hydllp JSON from a webservice
  
=head1 Usage

Specify the function as you would a Perl JSONCall. 

See the Hydstra help file for further examples. Specifically: HYDLLP - Flat DLL Interface to Hydstra

=head1 Screenshot 

=begin HTML

<p><img src="https://github.com/Chromicon/jsonimp/blob/master/images/PSC.PNG" alt="PSC" /></p>

=end HTML

=head1 Cut n Paste Examples

=head3 get_db_info

  {
    'function'=>'get_db_info',
    'version'=> 3,
    'params'=>{
      'table_name'=> 'site', 
      'return_type'=> 'array', 
      'decodes'=>'yes',
      'field_list'=> ['station', 'stname', 'latitude', 'longitude', 'zone'],
      'sitelist_filter'=>'GROUP(BORES,Geelong)'
    }	
  }

=head3 get_ts_traces

  { 
  'function'=> 'get_ts_traces', 
    'version'=> 2,
    'params'=> {
      'site_list'=> '142714', 
      'datasource'=> 'A', 
      'varfrom'=> '100.09', 
      'varto'=> '100.09', 
      'start_time'=> '20140701000000', 
      'end_time'=>'20140802000000', 
      'data_type'=> 'mean', 
      'interval'=> 'day', 
      'multiplier'=> '1'
    }
  }