=head1 VERSION

Version 0.01

=head1 SYNOPSIS

HYSCRIPT to import hydllp JSON from a webservice
  
     
=head1 Usage

Specify the function as you would a Perl JSONCall. 

See the Hydstra help file for further examples. Specifically: HYDLLP - Flat DLL Interface to Hydstra

=head1 Screenshot 

=begin HTML

<p><img src="https://github.com/Chromicon/jsonimp/blob/master/images/PSC.PNG" alt="PSC" /></p>

=end HTML
